releases:
  - name: dhis2-core
    namespace: dhis2-core
    chart: ../../helm/dhis2-core-helm/
    values:
      - ingress:
          enabled: true
          hosts:
            - host: dhis2-{{ requiredEnv "LB_IP" }}.nip.io
              paths:
                - path: /
                  backend:
                    serviceName: dhis2-{{ requiredEnv "LB_IP" }}.nip.io
                    servicePort: 8080

  - name: dhis2-core-database
    namespace: dhis2-core
    chart: bitnami/postgresql
    verify: false
    values:
      - extraEnv:
          - name: SEED_URL
            # TODO: requiredEnv "SEED_URL" ... Or from value?
            value: 2.36/dhis2-db-sierra-leone.sql.gz
      - initdbScripts:
          seed.sh: |
            #!/usr/bin/env bash
            ABSOLUTE_SEED_URL="https://databases.dhis2.org/sierra-leone/$SEED_URL"
            curl -o /tmp/z.$$ $ABSOLUTE_SEED_URL
            gunzip -c /tmp/z.$$ > /tmp/dhis2-db-sierra-leone.sql
            psql -U postgres -d dhis2 -p 5432 -f /tmp/dhis2-db-sierra-leone.sql
            rm /tmp/dhis2-db-sierra-leone.sql
      - image:
          tag: 10
      # TODO: Don't do this, set default storage class... Somewhere
      - global:
          storageClass: gp2
      - postgresqlUsername: dhis
        postgresqlPassword: dhis
        postgresqlDatabase: dhis2
        persistence:
          size: 5Gi
          storageClass: local-path

#  - name: whoami-mn
#    namespace: whoami
#    chart: tons/whoami-mn
#    verify: true
#    values:
#      - replicaCount: 2
#      - ingress:
#          enabled: true
#          hostname: whoami-mn-52.220.47.228.nip.io

  - name: whoami-go
    namespace: whoami
    chart: tons/whoami-go
    verify: true
    values:
      - replicaCount: 2
      - ingress:
          enabled: true
          hostname: whoami-go-{{ requiredEnv "LB_IP" }}.nip.io

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: tons
    url: https://helm-charts.fitfit.dk
