apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rbac.fullname" . }}
  labels:
    {{- include "rbac.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
      - "extensions"
      - "networking.k8s.io"
    resources:
      - "configmaps"
      - "cronjobs"
      - "deployments"
      - "events"
      - "ingresses"
      - "jobs"
      - "pods"
      - "pods/attach"
      - "pods/exec"
      - "pods/log"
      - "pods/portforward"
      - "secrets"
      - "services"
    verbs:
      - "create"
      - "delete"
      #- "describe"
      - "get"
      - "list"
      - "patch"
      - "update"
